# Generated by Django 2.0.5 on 2018-05-21 19:01

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_prof', models.BooleanField(default=False)),
                ('is_ra', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'sort feature',
            },
        ),
        migrations.CreateModel(
            name='mobile_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_companny', models.CharField(max_length=200, null=True)),
                ('mobile_name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('rating', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'mobile_phone',
            },
        ),
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Companny', models.CharField(max_length=200, null=True)),
                ('Mobile_Name', models.CharField(max_length=300, null=True)),
                ('Whats_new', models.TextField(null=True)),
                ('OS', models.CharField(max_length=300, null=True)),
                ('Dimensions', models.CharField(max_length=300, null=True)),
                ('Weight', models.CharField(max_length=100, null=True)),
                ('Colors', models.CharField(max_length=300, null=True)),
                ('Cpu', models.CharField(max_length=500, null=True)),
                ('Chip', models.CharField(max_length=500, null=True)),
                ('Gpu', models.CharField(max_length=500, null=True)),
                ('Size', models.CharField(max_length=300, null=True)),
                ('Resolution', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField(null=True)),
                ('rating', models.CharField(max_length=300, null=True)),
                ('image_path', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'phone',
            },
        ),
        migrations.CreateModel(
            name='samsung_phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Companny', models.CharField(max_length=200, null=True)),
                ('Mobile_Name', models.CharField(max_length=300, null=True)),
                ('Whats_new', models.TextField(null=True)),
                ('Chip', models.CharField(max_length=500, null=True)),
                ('Colors', models.CharField(max_length=300, null=True)),
                ('Cpu', models.CharField(max_length=500, null=True)),
                ('Dimensions', models.CharField(max_length=300, null=True)),
                ('Gpu', models.CharField(max_length=500, null=True)),
                ('Resolution', models.CharField(max_length=500, null=True)),
                ('Size', models.FloatField(null=True)),
                ('Weight', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('OS', models.CharField(max_length=300, null=True)),
                ('imagepath1', models.CharField(max_length=300, null=True)),
                ('imagepath2', models.CharField(max_length=300, null=True)),
                ('battery', models.CharField(max_length=400, null=True)),
                ('back_camera', models.CharField(max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'samsungphone',
            },
        ),
        migrations.CreateModel(
            name='signup_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300, null=True)),
                ('role', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sort_feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField(null=True)),
                ('feature', models.CharField(max_length=200, null=True)),
                ('position', models.IntegerField(null=True)),
                ('sh_hd', models.IntegerField(null=True)),
                ('roles', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'sort feature',
            },
        ),
    ]
